/**
 * Magic bytes and file signature database for VERIS classification.
 *
 * Provides known byte patterns for detecting file formats at specific offsets.
 *
 * @module @veris/classification/magic-bytes
 */

import type { MagicBytePattern } from './types.js';

/**
 * Known magic byte patterns for file format detection.
 * Ordered by specificity (more specific patterns first).
 */
export const MAGIC_BYTE_PATTERNS: readonly MagicBytePattern[] = [
  // === Executables ===
  {
    offset: 0,
    bytes: '7f454c46',
    category: 'executable',
    subType: 'ELF',
    mimeType: 'application/x-elf',
    confidence: 0.99,
    name: 'ELF (Executable and Linkable Format)',
  },
  {
    offset: 0,
    bytes: '4d5a',
    category: 'executable',
    subType: 'PE',
    mimeType: 'application/x-dosexec',
    confidence: 0.99,
    name: 'PE (Portable Executable)',
  },
  {
    offset: 0,
    bytes: 'cefaedfe',
    category: 'executable',
    subType: 'Mach-O',
    mimeType: 'application/x-mach-binary',
    confidence: 0.99,
    name: 'Mach-O (32-bit)',
  },
  {
    offset: 0,
    bytes: 'cffaedfe',
    category: 'executable',
    subType: 'Mach-O',
    mimeType: 'application/x-mach-binary',
    confidence: 0.99,
    name: 'Mach-O (64-bit)',
  },
  {
    offset: 0,
    bytes: 'feedface',
    category: 'executable',
    subType: 'Mach-O',
    mimeType: 'application/x-mach-binary',
    confidence: 0.99,
    name: 'Mach-O (PPC 32-bit)',
  },
  {
    offset: 0,
    bytes: 'feedfacf',
    category: 'executable',
    subType: 'Mach-O',
    mimeType: 'application/x-mach-binary',
    confidence: 0.99,
    name: 'Mach-O (PPC 64-bit)',
  },
  {
    offset: 0,
    bytes: 'cafebabe',
    category: 'executable',
    subType: 'Universal-Binary',
    mimeType: 'application/x-mach-binary',
    confidence: 0.95,
    name: 'Mach-O Universal Binary',
  },
  {
    offset: 0,
    bytes: 'cafed00d',
    category: 'executable',
    subType: 'JAR-Pack200',
    mimeType: 'application/x-java-pack200',
    confidence: 0.9,
    name: 'Java Pack200',
  },

  // === Archives ===
  {
    offset: 0,
    bytes: '504b0304',
    category: 'archive',
    subType: 'ZIP',
    mimeType: 'application/zip',
    confidence: 0.99,
    name: 'ZIP Archive',
  },
  {
    offset: 0,
    bytes: '504b0506',
    category: 'archive',
    subType: 'ZIP',
    mimeType: 'application/zip',
    confidence: 0.99,
    name: 'ZIP Archive (Empty)',
  },
  {
    offset: 0,
    bytes: '504b0708',
    category: 'archive',
    subType: 'ZIP',
    mimeType: 'application/zip',
    confidence: 0.99,
    name: 'ZIP Archive (Span)',
  },
  {
    offset: 0,
    bytes: '1f8b',
    category: 'archive',
    subType: 'GZIP',
    mimeType: 'application/gzip',
    confidence: 0.99,
    name: 'GZip Compressed',
  },
  {
    offset: 0,
    bytes: '1f9d',
    category: 'archive',
    subType: 'Compress',
    mimeType: 'application/x-compress',
    confidence: 0.9,
    name: 'Compress (.Z)',
  },
  {
    offset: 0,
    bytes: '1fa0',
    category: 'archive',
    subType: 'Compress',
    mimeType: 'application/x-compress',
    confidence: 0.9,
    name: 'Compress (.Z) (Alternate)',
  },
  {
    offset: 257,
    bytes: '757374617200',
    category: 'archive',
    subType: 'TAR',
    mimeType: 'application/x-tar',
    confidence: 0.95,
    name: 'TAR Archive (ustar)',
  },
  {
    offset: 257,
    bytes: '7573746172202000',
    category: 'archive',
    subType: 'TAR',
    mimeType: 'application/x-tar',
    confidence: 0.95,
    name: 'TAR Archive (gnutar)',
  },
  {
    offset: 0,
    bytes: '425a68',
    category: 'archive',
    subType: 'BZ2',
    mimeType: 'application/x-bzip2',
    confidence: 0.99,
    name: 'BZip2 Compressed',
  },
  {
    offset: 0,
    bytes: '377abcaf271c',
    category: 'archive',
    subType: '7z',
    mimeType: 'application/x-7z-compressed',
    confidence: 0.99,
    name: '7-Zip Archive',
  },
  {
    offset: 0,
    bytes: '526172211a0700',
    category: 'archive',
    subType: 'RAR',
    mimeType: 'application/vnd.rar',
    confidence: 0.99,
    name: 'RAR Archive (1.5)',
  },
  {
    offset: 0,
    bytes: '526172211a070100',
    category: 'archive',
    subType: 'RAR',
    mimeType: 'application/vnd.rar',
    confidence: 0.99,
    name: 'RAR Archive (5.0)',
  },
  {
    offset: 0,
    bytes: 'fd377a585a00',
    category: 'archive',
    subType: 'XZ',
    mimeType: 'application/x-xz',
    confidence: 0.99,
    name: 'XZ Compressed',
  },
  {
    offset: 0,
    bytes: '4c5a4950',
    category: 'archive',
    subType: 'LZIP',
    mimeType: 'application/x-lzip',
    confidence: 0.95,
    name: 'LZip Compressed',
  },
  {
    offset: 0,
    bytes: '28b52ffd',
    category: 'archive',
    subType: 'ZSTD',
    mimeType: 'application/zstd',
    confidence: 0.95,
    name: 'Zstandard Compressed',
  },
  {
    offset: 0,
    bytes: '1f8b08',
    category: 'archive',
    subType: 'GZIP',
    mimeType: 'application/gzip',
    confidence: 0.99,
    name: 'GZip Compressed (deflate)',
  },

  // === Documents ===
  {
    offset: 0,
    bytes: '25504446',
    category: 'document',
    subType: 'PDF',
    mimeType: 'application/pdf',
    confidence: 0.99,
    name: 'PDF Document',
  },
  {
    offset: 0,
    bytes: 'd0cf11e0a1b11ae1',
    category: 'document',
    subType: 'OLE2',
    mimeType: 'application/x-ole-storage',
    confidence: 0.99,
    name: 'OLE2 Compound Document (Office 97-2003)',
  },
  {
    offset: 0,
    bytes: '504b030414000600',
    category: 'document',
    subType: 'Office-Open-XML',
    mimeType: 'application/vnd.openxmlformats-officedocument',
    confidence: 0.95,
    name: 'Office Open XML Document',
  },

  // === Images ===
  {
    offset: 0,
    bytes: '89504e470d0a1a0a',
    category: 'image',
    subType: 'PNG',
    mimeType: 'image/png',
    confidence: 0.99,
    name: 'PNG Image',
  },
  {
    offset: 0,
    bytes: 'ffd8ffe0',
    category: 'image',
    subType: 'JPEG',
    mimeType: 'image/jpeg',
    confidence: 0.99,
    name: 'JPEG Image (JFIF)',
  },
  {
    offset: 0,
    bytes: 'ffd8ffe1',
    category: 'image',
    subType: 'JPEG',
    mimeType: 'image/jpeg',
    confidence: 0.99,
    name: 'JPEG Image (EXIF)',
  },
  {
    offset: 0,
    bytes: 'ffd8ffe2',
    category: 'image',
    subType: 'JPEG',
    mimeType: 'image/jpeg',
    confidence: 0.99,
    name: 'JPEG Image (ICC)',
  },
  {
    offset: 0,
    bytes: 'ffd8ffdb',
    category: 'image',
    subType: 'JPEG',
    mimeType: 'image/jpeg',
    confidence: 0.99,
    name: 'JPEG Image',
  },
  {
    offset: 0,
    bytes: '474946383761',
    category: 'image',
    subType: 'GIF',
    mimeType: 'image/gif',
    confidence: 0.99,
    name: 'GIF Image (87a)',
  },
  {
    offset: 0,
    bytes: '474946383961',
    category: 'image',
    subType: 'GIF',
    mimeType: 'image/gif',
    confidence: 0.99,
    name: 'GIF Image (89a)',
  },
  {
    offset: 0,
    bytes: '424d',
    category: 'image',
    subType: 'BMP',
    mimeType: 'image/bmp',
    confidence: 0.99,
    name: 'BMP Image',
  },
  {
    offset: 0,
    bytes: '49492a00',
    category: 'image',
    subType: 'TIFF',
    mimeType: 'image/tiff',
    confidence: 0.99,
    name: 'TIFF Image (Little Endian)',
  },
  {
    offset: 0,
    bytes: '4d4d002a',
    category: 'image',
    subType: 'TIFF',
    mimeType: 'image/tiff',
    confidence: 0.99,
    name: 'TIFF Image (Big Endian)',
  },
  {
    offset: 0,
    bytes: '00000100',
    category: 'image',
    subType: 'ICO',
    mimeType: 'image/x-icon',
    confidence: 0.99,
    name: 'ICO Icon',
  },

  // === Certificates ===
  {
    offset: 0,
    bytes: '2d2d2d2d2d424547494e',
    category: 'certificate',
    subType: 'PEM',
    mimeType: 'application/x-pem-file',
    confidence: 0.95,
    name: 'PEM Certificate/Key',
  },
  {
    offset: 0,
    bytes: '3082',
    category: 'certificate',
    subType: 'DER',
    mimeType: 'application/x-x509-ca-cert',
    confidence: 0.9,
    name: 'DER Certificate (Sequence)',
  },
  {
    offset: 0,
    bytes: '3081',
    category: 'certificate',
    subType: 'DER',
    mimeType: 'application/x-x509-ca-cert',
    confidence: 0.9,
    name: 'DER Certificate (Short Sequence)',
  },

  // === Scripts ===
  {
    offset: 0,
    bytes: '2321',
    category: 'script',
    subType: 'Shebang',
    mimeType: 'text/plain',
    confidence: 0.7,
    name: 'Shebang Script',
  },

  // === Java ===
  {
    offset: 0,
    bytes: 'cafebabe00000034',
    category: 'binary',
    subType: 'Java-Class',
    mimeType: 'application/x-java-class',
    confidence: 0.99,
    name: 'Java Class File (Java 8+)',
  },
  {
    offset: 0,
    bytes: 'cafebabe00000033',
    category: 'binary',
    subType: 'Java-Class',
    mimeType: 'application/x-java-class',
    confidence: 0.99,
    name: 'Java Class File (Java 7)',
  },
  {
    offset: 0,
    bytes: 'cafebabe00000032',
    category: 'binary',
    subType: 'Java-Class',
    mimeType: 'application/x-java-class',
    confidence: 0.99,
    name: 'Java Class File (Java 6)',
  },

  // === Windows ===
  {
    offset: 0,
    bytes: '4d534346',
    category: 'binary',
    subType: 'CAB',
    mimeType: 'application/vnd.ms-cab-compressed',
    confidence: 0.99,
    name: 'Microsoft CAB Archive',
  },
  {
    offset: 0,
    bytes: 'e011cfd0',
    category: 'binary',
    subType: 'Dos-Executable',
    mimeType: 'application/x-msdownload',
    confidence: 0.95,
    name: 'Windows Executable (Old)',
  },
];

/**
 * Known shebang interpreters for script detection.
 */
export const SHEBANG_PATTERNS: ReadonlyArray<{
  readonly pattern: string;
  readonly category: string;
  readonly subType: string;
  readonly mimeType: string;
}> = [
  { pattern: 'python', category: 'script', subType: 'Python', mimeType: 'text/x-python' },
  { pattern: 'python3', category: 'script', subType: 'Python3', mimeType: 'text/x-python' },
  { pattern: 'python2', category: 'script', subType: 'Python2', mimeType: 'text/x-python' },
  { pattern: 'node', category: 'script', subType: 'JavaScript', mimeType: 'text/javascript' },
  { pattern: 'deno', category: 'script', subType: 'JavaScript', mimeType: 'text/javascript' },
  { pattern: 'bun', category: 'script', subType: 'JavaScript', mimeType: 'text/javascript' },
  { pattern: 'bash', category: 'script', subType: 'Bash', mimeType: 'text/x-shellscript' },
  { pattern: 'sh', category: 'script', subType: 'Shell', mimeType: 'text/x-shellscript' },
  { pattern: 'zsh', category: 'script', subType: 'Shell', mimeType: 'text/x-shellscript' },
  { pattern: 'dash', category: 'script', subType: 'Shell', mimeType: 'text/x-shellscript' },
  { pattern: 'ksh', category: 'script', subType: 'Shell', mimeType: 'text/x-shellscript' },
  { pattern: 'fish', category: 'script', subType: 'Shell', mimeType: 'text/x-shellscript' },
  { pattern: 'ruby', category: 'script', subType: 'Ruby', mimeType: 'text/x-ruby' },
  { pattern: 'perl', category: 'script', subType: 'Perl', mimeType: 'text/x-perl' },
  { pattern: 'php', category: 'script', subType: 'PHP', mimeType: 'text/x-php' },
  { pattern: 'lua', category: 'script', subType: 'Lua', mimeType: 'text/x-lua' },
  { pattern: 'awk', category: 'script', subType: 'AWK', mimeType: 'text/x-awk' },
  { pattern: 'sed', category: 'script', subType: 'Sed', mimeType: 'text/x-sed' },
  { pattern: 'env wish', category: 'script', subType: 'Tcl', mimeType: 'text/x-tcl' },
  { pattern: 'guile', category: 'script', subType: 'Scheme', mimeType: 'text/x-scheme' },
  { pattern: 'racket', category: 'script', subType: 'Racket', mimeType: 'text/x-scheme' },
  { pattern: 'sbcl', category: 'script', subType: 'Common-Lisp', mimeType: 'text/x-common-lisp' },
  { pattern: 'clisp', category: 'script', subType: 'Common-Lisp', mimeType: 'text/x-common-lisp' },
  { pattern: 'groovy', category: 'script', subType: 'Groovy', mimeType: 'text/x-groovy' },
  { pattern: 'kotlin', category: 'script', subType: 'Kotlin', mimeType: 'text/x-kotlin' },
  { pattern: 'scala', category: 'script', subType: 'Scala', mimeType: 'text/x-scala' },
  { pattern: 'make', category: 'script', subType: 'Makefile', mimeType: 'text/x-makefile' },
  { pattern: 'pwsh', category: 'script', subType: 'PowerShell', mimeType: 'text/powershell' },
];

/**
 * Byte Order Mark (BOM) patterns for encoding detection.
 */
export const BOM_PATTERNS: ReadonlyArray<{
  readonly bytes: string;
  readonly encoding: string;
  readonly name: string;
}> = [
  { bytes: 'efbbbf', encoding: 'utf-8', name: 'UTF-8 BOM' },
  { bytes: 'fffe', encoding: 'utf-16le', name: 'UTF-16 Little Endian BOM' },
  { bytes: 'feff', encoding: 'utf-16be', name: 'UTF-16 Big Endian BOM' },
  { bytes: '0000feff', encoding: 'utf-32be', name: 'UTF-32 Big Endian BOM' },
  { bytes: 'fffe0000', encoding: 'utf-32le', name: 'UTF-32 Little Endian BOM' },
  { bytes: '2b2f76', encoding: 'utf-7', name: 'UTF-7 BOM' },
  { bytes: 'f7644c', encoding: 'utf-1', name: 'UTF-1 BOM' },
  { bytes: 'dd736673', encoding: 'utf-ebcdic', name: 'UTF-EBCDIC BOM' },
  { bytes: '0efe', encoding: 'scsu', name: 'SCSU BOM' },
  { bytes: 'fbee28', encoding: 'bocu-1', name: 'BOCU-1 BOM' },
  { bytes: '84d259', encoding: 'gb18030', name: 'GB-18030 BOM' },
];

/**
 * MIME type mapping from file extensions.
 */
export const EXTENSION_MIME_MAP: Record<string, string> = {
  '.py': 'text/x-python',
  '.pyw': 'text/x-python',
  '.js': 'text/javascript',
  '.jsx': 'text/jsx',
  '.ts': 'text/typescript',
  '.tsx': 'text/typescript',
  '.mjs': 'text/javascript',
  '.cjs': 'text/javascript',
  '.sh': 'text/x-shellscript',
  '.bash': 'text/x-shellscript',
  '.zsh': 'text/x-shellscript',
  '.ps1': 'text/powershell',
  '.psm1': 'text/powershell',
  '.psd1': 'text/powershell',
  '.bat': 'text/x-bat',
  '.cmd': 'text/x-bat',
  '.rb': 'text/x-ruby',
  '.rbw': 'text/x-ruby',
  '.pl': 'text/x-perl',
  '.pm': 'text/x-perl',
  '.php': 'text/x-php',
  '.phtml': 'text/x-php',
  '.lua': 'text/x-lua',
  '.tcl': 'text/x-tcl',
  '.java': 'text/x-java',
  '.rs': 'text/x-rust',
  '.go': 'text/x-go',
  '.swift': 'text/x-swift',
  '.kt': 'text/x-kotlin',
  '.scala': 'text/x-scala',
  '.json': 'application/json',
  '.yaml': 'text/yaml',
  '.yml': 'text/yaml',
  '.toml': 'text/toml',
  '.xml': 'application/xml',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.css': 'text/css',
  '.md': 'text/markdown',
  '.txt': 'text/plain',
  '.csv': 'text/csv',
  '.env': 'text/plain',
  '.cfg': 'text/plain',
  '.ini': 'text/plain',
  '.conf': 'text/plain',
  '.exe': 'application/x-msdownload',
  '.dll': 'application/x-msdownload',
  '.so': 'application/x-sharedlib',
  '.dylib': 'application/x-mach-binary',
  '.a': 'application/x-archive',
  '.o': 'application/x-object',
  '.class': 'application/x-java-class',
  '.jar': 'application/x-java-archive',
  '.war': 'application/x-java-archive',
  '.pdf': 'application/pdf',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.bmp': 'image/bmp',
  '.webp': 'image/webp',
  '.zip': 'application/zip',
  '.tar': 'application/x-tar',
  '.gz': 'application/gzip',
  '.tgz': 'application/gzip',
  '.bz2': 'application/x-bzip2',
  '.xz': 'application/x-xz',
  '.7z': 'application/x-7z-compressed',
  '.rar': 'application/vnd.rar',
  '.crt': 'application/x-x509-ca-cert',
  '.pem': 'application/x-pem-file',
  '.key': 'application/x-pem-file',
  '.cert': 'application/x-x509-ca-cert',
  '.p12': 'application/x-pkcs12',
  '.pfx': 'application/x-pkcs12',
  '.der': 'application/x-x509-ca-cert',
};

/**
 * Extension-to-category mapping for preliminary hints.
 */
export const EXTENSION_CATEGORY_MAP: Record<string, string> = {
  '.py': 'script',
  '.pyw': 'script',
  '.js': 'script',
  '.jsx': 'script',
  '.ts': 'script',
  '.tsx': 'script',
  '.mjs': 'script',
  '.cjs': 'script',
  '.sh': 'script',
  '.bash': 'script',
  '.zsh': 'script',
  '.ps1': 'script',
  '.psm1': 'script',
  '.psd1': 'script',
  '.bat': 'script',
  '.cmd': 'script',
  '.rb': 'script',
  '.rbw': 'script',
  '.pl': 'script',
  '.pm': 'script',
  '.php': 'script',
  '.phtml': 'script',
  '.lua': 'script',
  '.tcl': 'script',
  '.java': 'source-code',
  '.rs': 'source-code',
  '.go': 'source-code',
  '.swift': 'source-code',
  '.kt': 'source-code',
  '.scala': 'source-code',
  '.cpp': 'source-code',
  '.c': 'source-code',
  '.h': 'source-code',
  '.hpp': 'source-code',
  '.cs': 'source-code',
  '.fs': 'source-code',
  '.exe': 'executable',
  '.dll': 'executable',
  '.so': 'executable',
  '.dylib': 'executable',
  '.ex_': 'executable',
  '.zip': 'archive',
  '.tar': 'archive',
  '.gz': 'archive',
  '.tgz': 'archive',
  '.bz2': 'archive',
  '.xz': 'archive',
  '.7z': 'archive',
  '.rar': 'archive',
  '.json': 'configuration',
  '.yaml': 'configuration',
  '.yml': 'configuration',
  '.toml': 'configuration',
  '.ini': 'configuration',
  '.cfg': 'configuration',
  '.conf': 'configuration',
  '.env': 'configuration',
  '.xml': 'configuration',
  '.html': 'document',
  '.htm': 'document',
  '.md': 'document',
  '.pdf': 'document',
  '.txt': 'document',
  '.csv': 'document',
  '.doc': 'document',
  '.docx': 'document',
  '.xls': 'document',
  '.xlsx': 'document',
  '.ppt': 'document',
  '.pptx': 'document',
  '.png': 'image',
  '.jpg': 'image',
  '.jpeg': 'image',
  '.gif': 'image',
  '.svg': 'image',
  '.ico': 'image',
  '.bmp': 'image',
  '.webp': 'image',
  '.crt': 'certificate',
  '.pem': 'certificate',
  '.cert': 'certificate',
  '.key': 'certificate',
  '.p12': 'certificate',
  '.pfx': 'certificate',
  '.der': 'certificate',
};
